### PR TITLE
MQTT Client reworked

### PR DESCRIPTION
**Pull request by eku**
## Description

The MQTT client was vulnerable to the problem reported in issue #443.

The source code has been simplified, which fortunately results in a reduction of the code size.

During the review it will be noticed that the code urgently needs a revision regarding compiler warnings. I couldn't bring myself to do that in the short time available.

## Motivation and Context

Getting issue #443 finished. Hopefully Issue #536, which I was never able to reproduce myself, will also be resolved.

## How Has This Been Tested?

The changes run stable on my NETIO production systems.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the [code style of this project](http://www.ethersex.de/index.php/Contributing#Coding_Style).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by eku** [comment]
@michaelb42 wrote
> There are some gcc warnings left.

Yes, that's why I wrote
> During the review it will be noticed that the code urgently needs a revision regarding compiler warnings. 

I didn't mean to remove all warnings at once. I don't like the buffer management either, but the rewrite still has to wait.

**Comment by eku** [comment]
@stefan-muc could you please test this code?

**Comment by stefan-muc** [comment]
Tested it successfully this evening (as discussed in IRC). Thanks!

**Comment by michaelb42** [comment]
Is this one still open?

**Comment by eku** [comment]
@michaelb42 Yes, the PR is still up to date. However, the problem of #536  is not reproducible with Linux and must be analyzed by the author of the issue under Windows. Alternatively, we can accept the changes here, they have worked well for me since implementation, and #536 is handled separately from this PR.

**Pull request merged**
