### PR TITLE
fix uip, fix httplog

### PR DESCRIPTION
**Pull request by ferbar**
Changes in uip:
 * Fix: bug in state WAIT_TIME: waiting too long, consuming ressources
 * Fix: bug in state WAIT_TIME: remove sending ACK in this state
 * Add/cleanup: debugging

Changes in httlog:
 * Fix: race condition / memory leak if sending http requests too fast
 * Add: store uuid in eeprom
 * Add: ecmd commands
 * Fix: return value of ht ecmd

### CODE REVIEW

**Comment by ferbar** [comment]
this fixes the httplog.
sry don't have the time to create 5 separate pull requests. However these issues should be fixed

**Comment by michaelb42** [comment]
No time to change the PR so that it can be merged? This one can be closed then?

**Comment by ferbar** [comment]
nope. 1a5a9f7 is the commit which includes both modules.
I will create an issue referring to this pull request, maybe someone else will do it for you

**Comment by michaelb42** [comment]
Oh, please, stop that! It's not for me and it's not gratuitous. Each PR should fix one issue or add features to exactly one module. We will not accept such pile of junk PRs.

**Pull request closed without merging**
