### PR TITLE
Fix #487

### LINKED ISSUE #487: memory leak / race condition in httplog
httplog stops working if requests sent too fast

fixed in #484

### PR DESCRIPTION
**Pull request by eku**
## Description

As described in #487 there is probably a race condition if a new request should be send while a previous request has not been finished transmitting.
The inplementation uses
a) dynamically allocated message buffers
b) a queue to spool requests

## Motivation and Context
See #487 for context.

## How Has This Been Tested?
It's difficult to reproduce the race conditions. May be the orignal reporter @ferbar of the issue can test this.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] My code follows the [code style of this project](http://www.ethersex.de/index.php/Contributing#Coding_Style).
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

Config option HTTPLOG_BUFFER_LEN has been removed from code and documentation. **May break existing setups.**

### CODE REVIEW

**Comment by ferbar** [comment]
I think that there is still a race condition with httplog_tmp_buf
Lets say we have a 2nd httplog() request when the first hasn't finished yet:

```1.
httplog(message)
  httplog_queue.push(malloced_data)
  httplog_resolve_address()
    resolv_query(CONF_HTTPLOG_SERVICE, httplog_dns_query_cb);	 


<wait for address resolved>

httplog_dns_query_cb()
  if(uip_connect(ipaddr:port) )
    httplog_tmp_buf = pop(&httplog_queue);

<wait for conneced to http server - can take some time for example if ADSL is in down/connecting state>


2.
httplog(message)
  httplog_queue.push(malloced_data)
  httplog_resolve_address()
    httplog_dns_query_cb(NULL, ipaddr); // address is in cache => immediate call to httplog_dns_query_cb

    httplog_dns_query_cb()
      if(uip_connect(ipaddr:port) )
        httplog_tmp_buf = pop(&httplog_queue); // first http_log_tmp_buf is overridden und will never be free()d

<wait for conneced to http server>
```

I would suggest to remove httplog_tmp_buf completely - we have the queue - and do the queue.pop() in httplog_net_main(void)

**Comment by eku** [comment]
@ferbar wrote:
> I would suggest to remove httplog_tmp_buf completely - we have the queue - and do the queue.pop() in httplog_net_main(void)

queue.pop removes the messages, which makes problems if retransmission is required.

**Comment by eku** [comment]
@ferbar Christian, could please test the new version.

**Comment by eku** [comment]
@michaelb42 
> Compiles, one warning:
I guess this is a non-DEBUG build.

**Comment by ferbar** [comment]
@eku I like the peek() version a lot more
Would it make sense to set a max queue lenght? If the network is down the queue length will increase until malloc()s fail.

I think if UIP_TIME_WAIT_TIMEOUT occures then UIP_APPCALL() is missing and request_pending = 0; is never called.

Are you interessted in a PR for this 10 Lines? However changing behaviour in uip.c might be dangerous.
https://github.com/ethersex/ethersex/compare/master...ferbar:master#diff-44f614e08de1c4f67a28f359135c8b9dR718

**Comment by eku** [comment]
@michaelb42  I will update this PR when PR #549 has been merged.

**Comment by eku** [comment]
While testing these changes intensively, I noticed that the module ECMD has a problem if requests arrive too fast. I also noticed that many modules that use the DNS resolver do not handle errors correctly. But this is corrected in another PR.

@michaelb42  Please have a look at the newest version.

**Comment by michaelb42** [comment]
@ferbar Could you please test this version?

**Comment by michaelb42** [comment]
Test is still required.

**Pull request merged**
