### PR TITLE
Avoiding conditional directives that split up parts of statements.

### PR DESCRIPTION
**Pull request by flaviommedeiros**
A suggestion to compile entire statements and expressions, as suggested by code style guidelines from the Linux Kernel and practitioners.
- https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/CodingStyle#n892
- https://www.cqse.eu/en/blog/living-in-the-ifdef-hell/

It might improve code understanding, maintainability and error-proneness.

### CODE REVIEW

**Comment by eku** [comment]
Thanks for your suggestions, but did you check the impact on code size?

**Comment by flaviommedeiros** [comment]
I do not see a significant impact on the code size (I mean lines of code). In addition, compilers will optimize the final binary code. 

The key point I think is on improving understanding, maintainability and error proneness. However, there is a need to apply this type of refactorings across the source files. Don't you think it is useful for the project?

**Comment by eku** [comment]
@flaviommedeiros : In principle, I agree with you. But the resources of the AVR are limited and we should make every effort to not waste them. That's why I asked about the impact on memory usage. Do not trust the code optimizer.

You changes affect the bootloader, which is even more limited.

**Comment by michaelb42** [comment]
Suggest to close this one due to lack of interest.

**Pull request closed without merging**
