### PR TITLE
firmware hangs while initializing named pins on an HC595 port extension

### PR DESCRIPTION
**Pull request by mwue**
Using named pins on a port extender HC595 breaks the initialization process because some functions were called but not defined for this extension. 

The newly added functions make portio work for the not really existing registers DDRx and PINx in such an extension. They take arguments and return values like any HARD_IO port. Naturally, write of "0" to the DDR-register will not set this pin as an input pin.  

( the diff contains some white-space related changes, I did not made intentionally. Seems my editor doesn't like them. sorry for that.  )

### CODE REVIEW

**Comment by eku** [comment]
@mwue Hi Mike! What do you think about the caller checking for NULL instead of empty functions?

**Comment by mwue** [comment]
Hi Erik, 
I replaced all dummy functions with really working functions, because I found, that using dummy's isn't sufficient for initialization and further use. ( commit 576b016 ). Now all functions work as expected. Regarding the limitations of this port extension, e.g. writing to DDR has no effect, but reading from the ( non exisiting) DDR returns 0xFF, as the pins are all outputs.

**Comment by eku** [comment]
@mwue could you please squash your PR into one commit. Thanks.

**Comment by eku** [comment]
@mwue Waiting for cleaned up PR.

**Pull request closed without merging**
