### PR TITLE
Onewire send DS18XX temperatures to mqtt

### PR DESCRIPTION
**Pull request by AnDann**
## Description
Send the converted temperatures every poll cycle to a mqtt topic
the topicbase can be configured

## Motivation and Context
Easy implementation of temperature sensors to homeautomation systems like openHAB or every mqtt capable system.

## How Has This Been Tested?
Codebase runs on AVRNet IO for over 2 years
rebased and tested for some days again on same hardware

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [ X] My code follows the [code style of this project](http://www.ethersex.de/index.php/Contributing#Coding_Style).
- [ X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by eku** [comment]
@AnDann did you know that this is already available in ```control6/examples/mqtt.src```?

**Comment by AnDann** [comment]
No did not know that ^^

**Comment by florian-asche** [comment]
But still nice to have it in real code. Just enable and it will send data. Whould be cool to have this for all devices and protocols.

**Comment by eku** [comment]
@florian-asche 
> Whould be cool to have this for all devices and protocols.

Yeah, that'd be a fine thing. PR is welcome.

However, providing each module with an MQTT extension is not a good solution. The approach of the C6 script quoted above is better. There is a module that takes over for delivering the sensor data and responding to commands and the sensors and actuators are automatically used when the respective module is active. Something similar can be found in Tasmota, for example.

@AnDann I'm closing the PR for the above reasons.

**Pull request closed without merging**
