### PR TITLE
Use USART selection framework for EMS.

### PR DESCRIPTION
**Pull request by maniac103**

### CODE REVIEW

**Comment by eku** [comment]
USART for EMS is selected via pinning. If you change this, you'd better remove any existing pinning for EMS. Check out scripts/add-hardware.

**Comment by maniac103** [comment]
I kept the default as USART1, which was used hardcoded before. So in order to break existing configs, one has to actively set a value in the USART selection AFAICT.

**Comment by michaelb42** [comment]
Consulting the datasheets one may find, that the pin initialization in ems/ems_uart.c and also the pin-declaration in scripts/add-hardware is completely superfluous since the usart-initialization overrides the normal I/O pin control for TxD and RxD. Plz remove all occurences of EMS_UART_TX and the usart-selection from menuconfig should work as expected.

**Comment by maniac103** [comment]
@michaelb42 What's your suggested alternative for generating the (needed) break condition then? The USART hardware doesn't seem to be capable of that, which is why the EMS code manually pulls down the TX line for 10 bit times.

**Comment by michaelb42** [comment]
Ah, ic. One-time initialization of the TXD-pin I/O registers and only toggle TXEN when a break has to be send. OK, we all love such statements with uncommented sideeffects (:-1:). Anyway, having a USART choice via menuconfig and a more or less hardcoded TXD-pin ensures - in the best case - a bad user experience. Thankfully someone has pre-defined all the TXD and RXD pins in pinning/internals/hackery*.m4. Please throw away the EMS_UART_TX defines, replace the PIN_CLEAR and DDR_CONFIG_OUT statements with the following and test again:

    /* PIN_CLEAR(TXDn) */
    PORT_CHAR(usart(TXD, _PORT)) &= ~_BV(usart(TXD, _PIN));
    /* DDR_CONFIG_OUT(TXDn) */
    DDR_CHAR(usart(TXD, _PORT)) |= _BV(usart(TXD, _PIN))

This one heavily relies on recursive C-preprocessor concatenation magic. Be warned if you try to "simplify" it.

**Comment by maniac103** [comment]
@michaelb42 Thanks for the hint about the already present UART pin definitions, I wasn't aware of them. I modified the commit accordingly. I also added a second commit adding a comment about the break generation.

**Pull request merged**
