### PR TITLE
Issue #373: Introduce HI4 and LO4 macros

### PR DESCRIPTION
**Pull request by AnDann**
this belongs to issue 373

### CODE REVIEW

**Comment by eku** [comment]
Thanks for your contribution.
We should also have a common implementation (macro) for byte to ascii-hex conversion.

**Comment by AnDann** [comment]
do you think it should be in "bit-macros.h" or in "byte2hex.h". there are places where the byte2hex function could also used.

The byte2hex could changed to use NIBBLE_TO_HEX macro too, but it uses uppercase while NIBBLE_TO_HEX use lowecase.
```c
  // convert high nibble into hex ascii
  string[0] = HI4(value) + '0';
  if(string[0] > '9')
    string[0] += 'A' - '0' - 10;

  // convert low nibble into hex ascii
  string[1] = LO4(value) + '0';
  if (string[1] > '9')
    string[1] += 'A' - '0' - 10;
```

**Comment by eku** [comment]
Good point. NIBBLE_TO_HEX should be, of course, in byte2hex.h.

From the five files that define NIBBLE_TO_HEX three use uppercase and two use lowecase. IMO it will not harm modbus_ecmd and dyndns if they also use uppercase hex chars.

**Comment by AnDann** [comment]
adc/kty/ecmd.c did only define NIBBLE_TO_HEX but made no use of it.
I did run "autotest/batch-local-test -n" without errors but i dont use dyndns, modbus or i2c.

**Comment by michaelb42** [comment]
@AnDann could you please have a look at #404?

**Pull request merged**
